services:
  backend:
    build:
      context: ./bnb-backend
    ports:
      - "3000:3000"
    # Run the development server for hot-reloading
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./bnb-backend
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./bnb-backend/package.json

  frontend:
    build:
      context: ./bnb-frontend
    ports:
      - "8080:8080"
    # Run the development server for hot-reloading
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./bnb-frontend
          target: /app
          ignore:
            - node_modules/
            - .next/
        - action: rebuild
          path: ./bnb-frontend/package.json
